// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLJ82oWVrirR4QTyUoLMvSeFJrqu7C2EU',
    appId: '1:284448789703:web:58c8962246d3d5805f5ae2',
    messagingSenderId: '284448789703',
    projectId: 'quantum-laboratories',
    authDomain: 'quantum-laboratories.firebaseapp.com',
    storageBucket: 'quantum-laboratories.appspot.com',
    measurementId: 'G-LZ1YERVCBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUuYbgzS7kn5TvI74sU9qwC7w9cRPsfy4',
    appId: '1:284448789703:android:d3cc09c04cd16d755f5ae2',
    messagingSenderId: '284448789703',
    projectId: 'quantum-laboratories',
    storageBucket: 'quantum-laboratories.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHDWAM3dSdpz3fOJUM__caP0waRu8KFWw',
    appId: '1:284448789703:ios:81398cfdf9f0c4545f5ae2',
    messagingSenderId: '284448789703',
    projectId: 'quantum-laboratories',
    storageBucket: 'quantum-laboratories.appspot.com',
    iosBundleId: 'com.example.quantumlaboratories',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHDWAM3dSdpz3fOJUM__caP0waRu8KFWw',
    appId: '1:284448789703:ios:b3d6831d6463858e5f5ae2',
    messagingSenderId: '284448789703',
    projectId: 'quantum-laboratories',
    storageBucket: 'quantum-laboratories.appspot.com',
    iosBundleId: 'com.example.quantumlaboratories.RunnerTests',
  );
}
